package cab;

import java.util.Random;

public abstract class User {
	
	public static int id; //will make autogenerated later
	private String name;
	private int age;
	private Gender gender;
	private String address;
	
	public User(int id,String name,int age,Gender gender) {
		this.name =name;
		this.gender=gender;
		this.age = age;
		this.id = id; 
	}
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getAge() {
		return age;
	}
	public void setAge(int age) {
		this.age = age;
	}
	public Gender getGender() {
		return gender;
	}
	public void setGender(Gender gender) {
		this.gender = gender;
	}
	
	
	
}
